/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PanelAnimation;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class ConverterAnimation extends javax.swing.JFrame {

    /**
     * Creates new form ConverterAnimation
     */
    public ConverterAnimation() {
        
        setUndecorated(true); //eliminamos los controles del panel para que no puedan cerrar la ventana
        
       // initComponents(); //eliminamos este campo por que los componentes tapan al panel que creamos
        add(new PanelAnimation()); //creamos una instancia de la clase PanelAnimation y la agregamos a esta clase para poder mostrarla
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //cerramos solo esta ventana
        setResizable(false); //hacemos que no se pueda agrandarni achicar la ventana
        pack(); //ajustamos el tamaño de la ventana al tamaño del panel
        setLocationRelativeTo(null); //establecemos la ubicacion donde aparecera la ventana. null --> centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
        //creamos la GUI en el Hilo de Despacho de Eventos (EDT)
//        SwingUtilities.invokeLater(() -> {
//            JFrame ventana = new JFrame("Animación con Múltiples Imágenes");
//            ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            
//            // Añadimos nuestro panel de animación personalizado a la ventana
//            ventana.add(new PanelAnimation());
//            
//            ventana.pack(); // Ajusta el tamaño de la ventana al del panel
//            ventana.setLocationRelativeTo(null); // Centra la ventana
//            ventana.setVisible(true);
//        });

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
