/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerCoins;
import Controller.ConverterCodeApiToNameCountry;
import Controller.ConverterNamesCountryToCodeAPI;
import Model.Coins;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class ConverterFinal extends javax.swing.JFrame {
    FondoPanel fondoPanel = new FondoPanel();
    private final Coins currentCoins;
    
    /**
     * Creates new form ConverterFinal
     */
    public ConverterFinal() {
        this.setContentPane(fondoPanel);
        ControllerCoins cc = ControllerCoins.getInstance();
        this.currentCoins = cc.getCoin();
        
        initComponents();
        showAllData();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jlCountryOne = new javax.swing.JLabel();
        jlAmountOne = new javax.swing.JLabel();
        jlAmountTwo = new javax.swing.JLabel();
        jlCountryTwo = new javax.swing.JLabel();
        jlCurrencyTwo = new javax.swing.JLabel();
        jlCurrencyOne = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlCountryOne.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jlCountryOne.setForeground(new java.awt.Color(255, 255, 255));
        jlCountryOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCountryOne.setText("Pais");

        jlAmountOne.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jlAmountOne.setForeground(new java.awt.Color(255, 255, 255));
        jlAmountOne.setText("Cantidad");

        jlAmountTwo.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jlAmountTwo.setForeground(new java.awt.Color(255, 255, 255));
        jlAmountTwo.setText("Cantidad");

        jlCountryTwo.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jlCountryTwo.setForeground(new java.awt.Color(255, 255, 255));
        jlCountryTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCountryTwo.setText("Pais");

        jlCurrencyTwo.setFont(new java.awt.Font("MingLiU-ExtB", 1, 48)); // NOI18N
        jlCurrencyTwo.setForeground(new java.awt.Color(255, 255, 255));
        jlCurrencyTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCurrencyTwo.setText("$");
        jlCurrencyTwo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlCurrencyOne.setFont(new java.awt.Font("MingLiU-ExtB", 1, 48)); // NOI18N
        jlCurrencyOne.setForeground(new java.awt.Color(255, 255, 255));
        jlCurrencyOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCurrencyOne.setText("$");
        jlCurrencyOne.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnReturn.setBackground(new java.awt.Color(51, 255, 51));
        btnReturn.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        btnReturn.setText("New Change");
        btnReturn.setBorder(new javax.swing.border.MatteBorder(null));
        btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Result");

        jlResult.setFont(new java.awt.Font("Snap ITC", 3, 12)); // NOI18N
        jlResult.setForeground(new java.awt.Color(255, 255, 255));
        jlResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlResult.setText("32.32");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jlCountryOne, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlAmountOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(jlAmountTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlCountryTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jlCurrencyOne, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlResult, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlCurrencyTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCurrencyTwo)
                            .addComponent(jlCurrencyOne))
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlResult, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCountryOne)
                    .addComponent(jlAmountOne)
                    .addComponent(jlAmountTwo)
                    .addComponent(jlCountryTwo))
                .addGap(37, 37, 37)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        CurrencyConverter cc = new CurrencyConverter();
        cc.setVisible(true);
        cc.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed


    class FondoPanel extends JPanel {
        private Image image;
        
        @Override
        public void paint(Graphics graphics) {
            image = new ImageIcon(getClass().getResource("/Images/FondoCurrencyConverter.jpg")).getImage();
            
            graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(graphics);
        }
    }
    
    public void showSymbolLabel() {
        String selectedCountryOne = jlCountryOne.getText().toUpperCase();
        String SelectedCountryTwo = jlCountryTwo.getText().toUpperCase();
        
        String SymbolCoin1 = ConverterNamesCountryToCodeAPI.getCurrencySymbolByCountry(selectedCountryOne);
        String SymbolCoin2 = ConverterNamesCountryToCodeAPI.getCurrencySymbolByCountry(SelectedCountryTwo);
        
        jlCurrencyOne.setText(SymbolCoin1);
        jlCurrencyTwo.setText(SymbolCoin2);
    }
    
    private void addSymbolUpdateLabel(String coin1, String coin2) {
        jlCountryOne.setText(coin1);
        jlCountryTwo.setText(coin2);
        
        showSymbolLabel();
    }
    
    public void showAllData() {
        String codeBasePair = ConverterCodeApiToNameCountry.getCountryNameForCode(currentCoins.getBase_code_pair());
        String codeTargetPair = ConverterCodeApiToNameCountry.getCountryNameForCode(currentCoins.getTarget_code());
        
        addSymbolUpdateLabel(codeBasePair, codeTargetPair);
        jlAmountOne.setText(String.valueOf(currentCoins.getAmountToConvert()));
        jlAmountTwo.setText(String.valueOf(currentCoins.getRate()));
        jlResult.setText(String.valueOf(currentCoins.getResultConvertion()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlAmountOne;
    private javax.swing.JLabel jlAmountTwo;
    private javax.swing.JLabel jlCountryOne;
    private javax.swing.JLabel jlCountryTwo;
    private javax.swing.JLabel jlCurrencyOne;
    private javax.swing.JLabel jlCurrencyTwo;
    private javax.swing.JLabel jlResult;
    // End of variables declaration//GEN-END:variables
}
