/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerClients;
import Controller.ControllerCoins;
import Controller.ControllerRecord;
import Controller.ConverterNamesCountryToCodeAPI;
import Controller.PanelAnimation;
import Model.Client;
import Model.Clock;
import Model.Coins;
import Model.Rates;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;




/**
 *
 * @author USER
 */
public class CurrencyConverter extends javax.swing.JFrame {
    FondoPanel fondoPanel = new FondoPanel();
    Clock localTime = new Clock();
    Coins currentCoin;
    Client currentClient;
    ControllerCoins cc = ControllerCoins.getInstance();
    ControllerRecord record = ControllerRecord.getInstance();
    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        this.setContentPane(fondoPanel);
        
//        ControllerCoins cc = ControllerCoins.getInstance();
        this.currentCoin = cc.getCoin();
        
        ControllerClients nc = ControllerClients.getInstance();
        this.currentClient = nc.getClient();
        
        initComponents();
        
        showTimeAndDate();
        
        addSymbolUpdaterListener(jcCountry1);
        addSymbolUpdaterListener(jcCountry2);
        
        configureAndAssignRateUpdater();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void showTimeAndDate() {

        jlDate.setText(localTime.getDate());
        jlHour.setText(localTime.getTime());

        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jlDate.setText(localTime.getDate());
                jlHour.setText(localTime.getTime());
            }
        };

        Timer timer = new Timer(1000, action);
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcCountry1 = new javax.swing.JComboBox<>();
        jcCountry2 = new javax.swing.JComboBox<>();
        jlCoin1 = new javax.swing.JLabel();
        jlCoin2 = new javax.swing.JLabel();
        txtCoin1 = new javax.swing.JTextField();
        txtCoin2 = new javax.swing.JTextField();
        btnChange = new javax.swing.JButton();
        btnReuturn = new javax.swing.JButton();
        btnViewRates = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlDate = new javax.swing.JLabel();
        jlHour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcCountry1.setBackground(new java.awt.Color(0, 0, 0));
        jcCountry1.setForeground(new java.awt.Color(255, 255, 255));
        jcCountry1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Brasil", "Canada", "Colombia", "Chile", "China", "España", "Estados Unidos", "Francia", "Japon", "Mexico", "Peru", "Reino Unido", "Suiza" }));
        jcCountry1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));

        jcCountry2.setBackground(new java.awt.Color(0, 0, 0));
        jcCountry2.setForeground(new java.awt.Color(255, 255, 255));
        jcCountry2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Brasil", "Canada", "Colombia", "Chile", "China", "España", "Estados Unidos", "Francia", "Japon", "Mexico", "Peru", "Reino Unido", "Suiza" }));
        jcCountry2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        jcCountry2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlCoin1.setFont(new java.awt.Font("MingLiU-ExtB", 1, 48)); // NOI18N
        jlCoin1.setForeground(new java.awt.Color(255, 255, 255));
        jlCoin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCoin1.setText("$");
        jlCoin1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlCoin2.setFont(new java.awt.Font("MingLiU-ExtB", 1, 48)); // NOI18N
        jlCoin2.setForeground(new java.awt.Color(255, 255, 255));
        jlCoin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCoin2.setText("$");
        jlCoin2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtCoin1.setBackground(new java.awt.Color(0, 0, 0));
        txtCoin1.setForeground(new java.awt.Color(255, 255, 255));
        txtCoin1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        txtCoin1.setCaretColor(new java.awt.Color(255, 255, 255));

        txtCoin2.setEditable(false);
        txtCoin2.setBackground(new java.awt.Color(0, 0, 0));
        txtCoin2.setForeground(new java.awt.Color(255, 255, 255));
        txtCoin2.setText("1.1");
        txtCoin2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        txtCoin2.setCaretColor(new java.awt.Color(255, 255, 255));

        btnChange.setBackground(new java.awt.Color(51, 255, 51));
        btnChange.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        btnChange.setText("Convert");
        btnChange.setBorder(new javax.swing.border.MatteBorder(null));
        btnChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnReuturn.setBackground(new java.awt.Color(0, 0, 0));
        btnReuturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReuturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        btnReuturn.setBorder(null);
        btnReuturn.setContentAreaFilled(false);
        btnReuturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReuturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReuturnActionPerformed(evt);
            }
        });

        btnViewRates.setForeground(new java.awt.Color(255, 255, 102));
        btnViewRates.setText("View rates");
        btnViewRates.setBorder(null);
        btnViewRates.setContentAreaFilled(false);
        btnViewRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRatesActionPerformed(evt);
            }
        });

        btnRecord.setForeground(new java.awt.Color(255, 255, 102));
        btnRecord.setText("Record");
        btnRecord.setBorder(null);
        btnRecord.setContentAreaFilled(false);
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Palace Script MT", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jLabel3.setText("Nemesis");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N
        btnProfile.setBorder(null);
        btnProfile.setContentAreaFilled(false);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora:");

        jlDate.setForeground(new java.awt.Color(255, 255, 255));
        jlDate.setText("10/10/2024");
        jlDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jlDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlHour.setForeground(new java.awt.Color(255, 255, 255));
        jlHour.setText("20:21");
        jlHour.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jlHour.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jcCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtCoin1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCoin2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcCountry2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewRates)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProfile)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReuturn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlDate, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jlHour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jlCoin1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlCoin2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewRates)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnReuturn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRecord))
                            .addComponent(btnProfile)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jlHour))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCoin1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCoin2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcCountry2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        // TODO add your handling code here:
        RecordUser ru = new RecordUser();
        ru.setVisible(true);
        ru.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnReuturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReuturnActionPerformed
        // TODO add your handling code here:
        LoginUser lu = new LoginUser();
        lu.setVisible(true);
        lu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnReuturnActionPerformed

    private void btnViewRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRatesActionPerformed
        // TODO add your handling code here:
        ViewRatesUser vru = new ViewRatesUser();
        vru.setVisible(true);
        vru.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewRatesActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        ProfileUser pu = new ProfileUser();
        pu.setVisible(true);
        pu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        try{
            if (txtCoin1.getText().isEmpty() || txtCoin2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "tienes que llenar los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(validateCoins(txtCoin1.getText())) {
                
                JOptionPane.showMessageDialog(this, "debes ingresar un numero, acepta como minimo 2 decimales", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            
            } 
            
            Double valueCoin1 = Double.parseDouble(txtCoin1.getText());
//            Double valueCoin2 = Double.parseDouble(txtCoin2.getText());

            if (valueCoin1 <= 0) {
                
                JOptionPane.showMessageDialog(this, "El numero debe ser positivo y no debe ser 0", "Error", JOptionPane.ERROR_MESSAGE);
                return;
                
            }
            
            String currentDate = localTime.getDate();
            String currentHour = localTime.getTime();
            
            String codebase = ConverterNamesCountryToCodeAPI.getCodeForCountryName(jcCountry1.getSelectedItem().toString().toUpperCase());
            String codeTarget = ConverterNamesCountryToCodeAPI.getCodeForCountryName(jcCountry2.getSelectedItem().toString().toUpperCase());
            
            cc.converterCoin(codebase, codeTarget, valueCoin1);
            
            double result = Double.parseDouble(txtCoin1.getText()) * Double.parseDouble(txtCoin2.getText());
            
            currentCoin.setBase_code_pair(codebase);
            currentCoin.setTarget_code(codeTarget);
            currentCoin.setAmountToConvert(Double.parseDouble(txtCoin1.getText()));
            currentCoin.setRate(Double.parseDouble(txtCoin2.getText()));
            currentCoin.setResultConvertion(result);
            
            record.saveRecord(currentClient, currentHour, currentDate, currentCoin);
            
            new ConverterAnimation().setVisible(true);
            this.dispose();
            
        }catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "ocurrio un error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_btnChangeActionPerformed
    
    class FondoPanel extends JPanel {
        private Image image;
        
        @Override
        public void paint(Graphics graphics) {
            image = new ImageIcon(getClass().getResource("/Images/FondoCurrencyConverter.jpg")).getImage();
            
            graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(graphics);
        }
    }
    
    public boolean validateCoins(String coin) {
        return !coin.matches("(\\d+(\\.\\d{1,2})?)|(\\.\\d{1,2})");
    }
    
    public void showSymbol(){
        String selectedCountry1 = jcCountry1.getSelectedItem().toString().toUpperCase();
        String symbolCoin1 = ConverterNamesCountryToCodeAPI.getCurrencySymbolByCountry(selectedCountry1);
        
        String selectedCountry2 = jcCountry2.getSelectedItem().toString().toUpperCase();
        String symbolCoin2 = ConverterNamesCountryToCodeAPI.getCurrencySymbolByCountry(selectedCountry2);
        
        jlCoin1.setText(symbolCoin1);
        jlCoin2.setText(symbolCoin2);
    }
    
    private void addSymbolUpdaterListener(JComboBox<?> comboBox) {
        comboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Llama a tu método principal de actualización
                showSymbol(); 
            }
        });
    }
    
    public void showRateCoin(String data1, String data2) {
        
        if (data1.isEmpty() || data2.isEmpty()) {
            // No hacer nada o mostrar un mensaje de error al usuario
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un código de moneda válido.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return; // Detiene la ejecución
        }
        
        String codeApi1 = ConverterNamesCountryToCodeAPI.getCodeForCountryName(data1); //convierte el pais ingresado a su simbolo api
        String codeApi2 = ConverterNamesCountryToCodeAPI.getCodeForCountryName(data2); //convierte el pais ingresado a su simbolo api
        
        double tasaObtenida = cc.showRates(codeApi1, codeApi2);
        
        String tasa = String.valueOf(tasaObtenida);
        
        txtCoin2.setText(tasa);
    }
    
    public void configureAndAssignRateUpdater() {

        // 1. Define el ActionListener usando una expresión lambda.
        // Esta expresión contiene la lógica de obtención de las selecciones y la llamada de actualización.
        ActionListener rateUpdater = e -> {

            // Obtener la selección actual de AMBOS ComboBoxes
            String baseCountryName = jcCountry1.getSelectedItem().toString();
            String targetCountryName = jcCountry2.getSelectedItem().toString(); 

            // Llamar al método que realiza el cálculo de la tasa
            showRateCoin(baseCountryName, targetCountryName); 
        };

        // 2. Asignar el mismo ActionListener a ambos JComboBox.
        jcCountry1.addActionListener(rateUpdater);
        jcCountry2.addActionListener(rateUpdater);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnReuturn;
    private javax.swing.JButton btnViewRates;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcCountry1;
    private javax.swing.JComboBox<String> jcCountry2;
    private javax.swing.JLabel jlCoin1;
    private javax.swing.JLabel jlCoin2;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlHour;
    private javax.swing.JTextField txtCoin1;
    private javax.swing.JTextField txtCoin2;
    // End of variables declaration//GEN-END:variables
}
