/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerClients;
import Model.Client;
import SaveData.ClientRepositoryCSV;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class LoginUser extends javax.swing.JFrame {
    private Point point;
    ControllerClients nc = ControllerClients.getInstance();
    /**
     * Creates new form LoginUser
     */
    public LoginUser() {
        initComponents();
        LoginUser.this.setBackground(new Color(0,0,0,0));
        this.lbDisguise.setVisible(false);
        this.txtPassword.setEchoChar('⚫');
        
        // Esta ventana principal es la única
        // que tiene el código de guardado.
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                
                System.out.println("Cerrando app. Guardando datos...");
                
                // Obtenemos los datos FRESCOS del controlador
                List<Client> listaParaGuardar = (List<Client>) nc.getClients();
                
                // Guardamos
                ClientRepositoryCSV manejador = new ClientRepositoryCSV();
                manejador.guardarDatos(listaParaGuardar);
                
                System.out.println("Datos guardados. Adiós.");
                
                // Cerramos
                e.getWindow().dispose();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        jpLogin = new javax.swing.JPanel();
        lbShow = new javax.swing.JLabel();
        lbDisguise = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSingup = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jlPhrase = new javax.swing.JLabel();
        jlFondoLoginUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setFont(new java.awt.Font("Maiandra GD", 3, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BTN_X.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        jpLogin.setBackground(new java.awt.Color(255, 255, 102));
        jpLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 51), new java.awt.Color(0, 255, 51), new java.awt.Color(0, 255, 51), new java.awt.Color(0, 255, 51)));
        jpLogin.setLayout(null);

        lbShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver_32px.png"))); // NOI18N
        lbShow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbShowMouseClicked(evt);
            }
        });
        jpLogin.add(lbShow);
        lbShow.setBounds(320, 210, 32, 32);

        lbDisguise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDisguise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocultar_32px.png"))); // NOI18N
        lbDisguise.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDisguise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDisguiseMouseClicked(evt);
            }
        });
        jpLogin.add(lbDisguise);
        lbDisguise.setBounds(320, 210, 32, 32);

        lbTitle.setFont(new java.awt.Font("Palatino Linotype", 3, 48)); // NOI18N
        lbTitle.setText("Login");
        jpLogin.add(lbTitle);
        lbTitle.setBounds(111, 57, 122, 66);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jLabel1.setText("Username:");
        jpLogin.add(jLabel1);
        jLabel1.setBounds(10, 170, 80, 21);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jLabel2.setText("Password:");
        jpLogin.add(jLabel2);
        jLabel2.setBounds(10, 220, 80, 21);

        txtUser.setBackground(new java.awt.Color(255, 255, 102));
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jpLogin.add(txtUser);
        txtUser.setBounds(92, 169, 243, 18);
        txtUser.getAccessibleContext().setAccessibleName("");
        txtUser.getAccessibleContext().setAccessibleDescription("");

        txtPassword.setBackground(new java.awt.Color(255, 255, 102));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jpLogin.add(txtPassword);
        txtPassword.setBounds(90, 220, 243, 18);

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Log in");
        btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jpLogin.add(btnLogin);
        btnLogin.setBounds(130, 280, 108, 21);

        btnSingup.setBackground(new java.awt.Color(255, 255, 102));
        btnSingup.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        btnSingup.setForeground(new java.awt.Color(0, 153, 0));
        btnSingup.setText("Sing up");
        btnSingup.setBorder(null);
        btnSingup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingupActionPerformed(evt);
            }
        });
        jpLogin.add(btnSingup);
        btnSingup.setBounds(220, 330, 49, 17);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        jLabel3.setText("I don't have an account");
        jpLogin.add(jLabel3);
        jLabel3.setBounds(100, 330, 130, 17);

        getContentPane().add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 350, 400));

        jlLogo.setFont(new java.awt.Font("Old English Text MT", 3, 24)); // NOI18N
        jlLogo.setForeground(new java.awt.Color(51, 255, 51));
        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jlLogo.setText("Nemesis");
        getContentPane().add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 80));

        jlPhrase.setBackground(new java.awt.Color(255, 255, 255));
        jlPhrase.setFont(new java.awt.Font("SimSun-ExtB", 3, 16)); // NOI18N
        jlPhrase.setForeground(new java.awt.Color(51, 255, 51));
        jlPhrase.setText("\"Welcome to Nemesis Currency Converter\"");
        getContentPane().add(jlPhrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jlFondoLoginUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFondoLoginUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoLoginUser.png"))); // NOI18N
        getContentPane().add(jlFondoLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        //para cerrar el programa al hacer click en el botom
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        //guardamos el dato del movimiento en una variable point usando evt.getPoint()
        point = evt.getPoint();
        
        // sobreescribimos el dato
        getComponentAt(point);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
         //calculamos las nuevas coordenadas x y y en nuestro formulario
        
        //guardamos las posiciones de x y y actuales en variables
        int currentX = this.getLocation().x;
        int currentY = this.getLocation().y;
        
        //calculamos el movimiento en x y y a travez de este evento y lo guardamos en variables
        int moveX = (currentX + evt.getX()) - (currentX + point.x);
        int moveY = (currentY + evt.getY()) - (currentY + point.y);
        
        //calculamos la nueva posicion en x y y
        int x = currentX+ moveX;
        int y = currentY+ moveY;
        
        // pasamos las nuevas posiciones x y y
        this.setLocation(x, y);
    }//GEN-LAST:event_formMouseDragged

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (nc.validateLogin(txtUser.getText(), txtPassword.getText())) {
            
            JOptionPane.showMessageDialog(
               this, // Ventana padre (donde se centra el mensaje)
               "¡Bienvenido/a, " + nc.getClient().getName() + " " + nc.getClient().getLastName()  + "!", // El mensaje a mostrar
               "Inicio de Sesión Exitoso", // Título de la ventana
               JOptionPane.INFORMATION_MESSAGE // Tipo de icono (informativo)
            );
            
            CurrencyConverter cc = new CurrencyConverter();
            cc.setVisible(true);
            cc.setLocationRelativeTo(null);
            this.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(this, "Usuario no registrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSingupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingupActionPerformed
        // TODO add your handling code here:
        SingUpUser suu = new SingUpUser();
        suu.setVisible(true);
        suu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnSingupActionPerformed

    private void lbShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbShowMouseClicked
        // TODO add your handling code here:
        lbShow.setVisible(false);
        lbDisguise.setVisible(true);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lbShowMouseClicked

    private void lbDisguiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDisguiseMouseClicked
        // TODO add your handling code here:
        lbDisguise.setVisible(false);
        lbShow.setVisible(true);
        txtPassword.setEchoChar('⚫');
    }//GEN-LAST:event_lbDisguiseMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSingup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlFondoLoginUser;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlPhrase;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JLabel lbDisguise;
    private javax.swing.JLabel lbShow;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
