/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerClients;
import Model.Client;
import java.awt.Graphics;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class ProfileUser extends javax.swing.JFrame {
    FondoPanel fondoPanel = new FondoPanel();
    ControllerClients cc = ControllerClients.getInstance();
    Client cliente;
    
    /**
     * Creates new form ProfileUser
     */
    public ProfileUser() {
        this.setContentPane(fondoPanel);
        this.cliente = cc.getClient();
        
        initComponents();
        txtPassword.setEchoChar('⚫');
        addTextInTheProfile();
        
        // hacemos que los text field y text area no se puedn editar
        txtAge.setEditable(false);
        txtCountry.setEditable(false);
        txtDescription.setEditable(false);
        txtGmail.setEditable(false);
        txtPassword.setEditable(false);
        txtUsername.setEditable(false);
        
        //hacemos que no aparesca el caret al iniciar y solo aparesca cuando se va a editar
        txtAge.setCaretColor(new java.awt.Color(0,0,0,0));
        txtCountry.setCaretColor(new java.awt.Color(0,0,0,0));
        txtDescription.setCaretColor(new java.awt.Color(0,0,0,0));
        txtGmail.setCaretColor(new java.awt.Color(0,0,0,0));
        txtPassword.setCaretColor(new java.awt.Color(0,0,0,0));
        txtUsername.setCaretColor(new java.awt.Color(0,0,0,0));
        
        //hacemos que los iconos de check desaparescan
        btnCheckAge.setVisible(false);
        btnCheckCountry.setVisible(false);
        btnCheckDescription.setVisible(false);
        btnCheckGmail.setVisible(false);
        btnCheckPassword.setVisible(false);
        btnCheckUser.setVisible(false);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNameLastname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnReturn = new javax.swing.JButton();
        btnEditGmail = new javax.swing.JButton();
        btnEditAge = new javax.swing.JButton();
        btnEditCountry = new javax.swing.JButton();
        btnEditUsername = new javax.swing.JButton();
        btnEditPassword = new javax.swing.JButton();
        btnEditDescription = new javax.swing.JButton();
        btnCheckGmail = new javax.swing.JButton();
        btnCheckAge = new javax.swing.JButton();
        btnCheckCountry = new javax.swing.JButton();
        btnCheckUser = new javax.swing.JButton();
        btnCheckPassword = new javax.swing.JButton();
        btnCheckDescription = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlGender = new javax.swing.JLabel();
        jlCode = new javax.swing.JLabel();
        btnShowPass = new javax.swing.JButton();
        btnDisguisePass = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNameLastname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNameLastname.setText("Name LastName");
        jlNameLastname.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlNameLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 301, -1));

        jLabel2.setText("Gmail:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 83, 37, -1));
        getContentPane().add(txtGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 80, 325, -1));

        jLabel3.setText("Age:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 125, -1, -1));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 122, 40, -1));

        jLabel4.setText("Country:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 125, -1, -1));

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });
        getContentPane().add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 122, 124, -1));

        jLabel5.setText("Username:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 167, -1, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 164, 325, -1));

        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 209, -1, -1));

        jLabel7.setText("Description:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 248, -1, -1));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 248, 325, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        btnReturn.setBorder(null);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        btnEditGmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnEdit.png"))); // NOI18N
        btnEditGmail.setBorder(null);
        btnEditGmail.setContentAreaFilled(false);
        btnEditGmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditGmailMouseClicked(evt);
            }
        });
        btnEditGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGmailActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 78, -1, -1));

        btnEditAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnEdit.png"))); // NOI18N
        btnEditAge.setBorder(null);
        btnEditAge.setContentAreaFilled(false);
        btnEditAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditAgeMouseClicked(evt);
            }
        });
        btnEditAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAgeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 120, -1, -1));

        btnEditCountry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnEdit.png"))); // NOI18N
        btnEditCountry.setBorder(null);
        btnEditCountry.setContentAreaFilled(false);
        btnEditCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCountryMouseClicked(evt);
            }
        });
        getContentPane().add(btnEditCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        btnEditUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnEdit.png"))); // NOI18N
        btnEditUsername.setBorder(null);
        btnEditUsername.setContentAreaFilled(false);
        btnEditUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditUsernameMouseClicked(evt);
            }
        });
        getContentPane().add(btnEditUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 163, -1, -1));

        btnEditPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnEdit.png"))); // NOI18N
        btnEditPassword.setBorder(null);
        btnEditPassword.setContentAreaFilled(false);
        btnEditPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditPasswordMouseClicked(evt);
            }
        });
        btnEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 207, -1, -1));

        btnEditDescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnEdit.png"))); // NOI18N
        btnEditDescription.setBorder(null);
        btnEditDescription.setContentAreaFilled(false);
        btnEditDescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditDescriptionMouseClicked(evt);
            }
        });
        getContentPane().add(btnEditDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 245, -1, -1));

        btnCheckGmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCheck.png"))); // NOI18N
        btnCheckGmail.setBorder(null);
        btnCheckGmail.setContentAreaFilled(false);
        btnCheckGmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckGmailMouseClicked(evt);
            }
        });
        btnCheckGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckGmailActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 78, -1, -1));

        btnCheckAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCheck.png"))); // NOI18N
        btnCheckAge.setBorder(null);
        btnCheckAge.setContentAreaFilled(false);
        btnCheckAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckAgeMouseClicked(evt);
            }
        });
        getContentPane().add(btnCheckAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 120, -1, -1));

        btnCheckCountry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCheck.png"))); // NOI18N
        btnCheckCountry.setBorder(null);
        btnCheckCountry.setContentAreaFilled(false);
        btnCheckCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckCountryMouseClicked(evt);
            }
        });
        getContentPane().add(btnCheckCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        btnCheckUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCheck.png"))); // NOI18N
        btnCheckUser.setBorder(null);
        btnCheckUser.setContentAreaFilled(false);
        btnCheckUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckUserMouseClicked(evt);
            }
        });
        getContentPane().add(btnCheckUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 163, -1, -1));

        btnCheckPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCheck.png"))); // NOI18N
        btnCheckPassword.setBorder(null);
        btnCheckPassword.setContentAreaFilled(false);
        btnCheckPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(btnCheckPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 207, -1, -1));

        btnCheckDescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCheck.png"))); // NOI18N
        btnCheckDescription.setBorder(null);
        btnCheckDescription.setContentAreaFilled(false);
        btnCheckDescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckDescriptionMouseClicked(evt);
            }
        });
        getContentPane().add(btnCheckDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 245, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Keep");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, -1));

        jLabel1.setText("Genero:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jlGender.setText("Masculino");
        getContentPane().add(jlGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jlCode.setText("codigo");
        getContentPane().add(jlCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        btnShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver_32px.png"))); // NOI18N
        btnShowPass.setToolTipText("");
        btnShowPass.setBorder(null);
        btnShowPass.setContentAreaFilled(false);
        btnShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPassActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 204, 32, 32));

        btnDisguisePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocultar_32px.png"))); // NOI18N
        btnDisguisePass.setBorder(null);
        btnDisguisePass.setContentAreaFilled(false);
        btnDisguisePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisguisePassActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisguisePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 204, 32, 32));

        txtPassword.setEditable(false);
        txtPassword.setText("jPasswordField1");
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 210, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void btnEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditPasswordActionPerformed

    private void btnEditAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditAgeActionPerformed

    private void btnEditGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditGmailActionPerformed

    private void btnCheckGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckGmailActionPerformed

    private void btnEditGmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditGmailMouseClicked
        // TODO add your handling code here:
        edit(txtGmail, btnCheckGmail, btnEditGmail);
    }//GEN-LAST:event_btnEditGmailMouseClicked
    private void btnCheckGmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckGmailMouseClicked
        // TODO add your handling code here:
        check(txtGmail, btnEditGmail, btnCheckGmail);
    }//GEN-LAST:event_btnCheckGmailMouseClicked

    private void btnEditAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditAgeMouseClicked
        // TODO add your handling code here:
        edit(txtAge, btnCheckAge, btnEditAge);
    }//GEN-LAST:event_btnEditAgeMouseClicked

    private void btnCheckAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckAgeMouseClicked
        // TODO add your handling code here:
        check(txtAge, btnEditAge, btnCheckAge);
    }//GEN-LAST:event_btnCheckAgeMouseClicked

    private void btnEditCountryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCountryMouseClicked
        // TODO add your handling code here:
        edit(txtCountry, btnCheckCountry, btnEditCountry);
    }//GEN-LAST:event_btnEditCountryMouseClicked

    private void btnCheckCountryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckCountryMouseClicked
        // TODO add your handling code here:
        check(txtCountry, btnEditCountry, btnCheckCountry);
    }//GEN-LAST:event_btnCheckCountryMouseClicked

    private void btnEditPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPasswordMouseClicked
        // TODO add your handling code here:
        edit(txtPassword, btnCheckPassword, btnEditPassword);
    }//GEN-LAST:event_btnEditPasswordMouseClicked

    private void btnCheckPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckPasswordMouseClicked
        // TODO add your handling code here:
        check(txtPassword, btnEditPassword, btnCheckPassword);
    }//GEN-LAST:event_btnCheckPasswordMouseClicked

    private void btnEditDescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditDescriptionMouseClicked
        // TODO add your handling code here:
        txtDescription.setEditable(true);
        txtDescription.setCaretColor(new java.awt.Color(0,0,0));
        btnEditDescription.setVisible(false);
        btnCheckDescription.setVisible(true);
    }//GEN-LAST:event_btnEditDescriptionMouseClicked

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        CurrencyConverter cc = new CurrencyConverter();
        cc.setVisible(true);
        cc.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnCheckDescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckDescriptionMouseClicked
        // TODO add your handling code here:
        txtDescription.setEditable(false);
        txtDescription.setCaretColor(new java.awt.Color(0,0,0,0));
        btnCheckDescription.setVisible(false);
        btnEditDescription.setVisible(true);
    }//GEN-LAST:event_btnCheckDescriptionMouseClicked

    private void btnEditUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditUsernameMouseClicked
        // TODO add your handling code here:
        edit(txtUsername, btnCheckUser, btnEditUsername);
    }//GEN-LAST:event_btnEditUsernameMouseClicked

    private void btnCheckUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckUserMouseClicked
        // TODO add your handling code here:
        check(txtUsername, btnEditUsername, btnCheckUser);
    }//GEN-LAST:event_btnCheckUserMouseClicked

    private void btnShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPassActionPerformed
        // TODO add your handling code here:
        if(txtPassword.isEditable()){
            btnShowPass.setVisible(false);
            btnDisguisePass.setVisible(true);
            txtPassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_btnShowPassActionPerformed

    private void btnDisguisePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisguisePassActionPerformed
        // TODO add your handling code here:
        if (txtPassword.isEditable()) {
            btnShowPass.setVisible(true);
            btnDisguisePass.setVisible(false);
            txtPassword.setEchoChar('⚫');
        }
    }//GEN-LAST:event_btnDisguisePassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtAge.getText().isEmpty() || txtCountry.getText().isEmpty() || txtDescription.getText().isEmpty() || txtGmail.getText().isEmpty() 
                || txtPassword.getText().isEmpty() || txtUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hay campos vacios", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (validateAge(txtAge.getText())) {
            JOptionPane.showMessageDialog(this, "La edad solo admite numeros enteros y positivos", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (txtDescription.getText().length() <= 10 || txtDescription.getText().length() >= 600) {
            JOptionPane.showMessageDialog(this, "El espacion para la descripcion admiten desde 10 a 600 caracteres"
                    , "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //validamos el campo del username
        boolean user = false;
        Pattern patronUsuario = Pattern.compile("^\\w+@nemesis\\.com$");
        Matcher users = patronUsuario.matcher(txtUsername.getText());
        user = users.matches();

        //validamos el campo del password
        boolean password = false;
        Pattern patronPassword=Pattern.compile("\\S{8,}");
        String textPass = new String(txtPassword.getPassword());
        Matcher passwords = patronPassword.matcher(textPass);
        password = passwords.matches();
        
        //validamos el gmail
        boolean gMail = false;
        Pattern patronGmail = Pattern.compile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$");
        Matcher gmail = patronGmail.matcher(txtGmail.getText());
        gMail = gmail.matches();

        //validamos que se cumplan las condiciones
        if(gMail == false){
          JOptionPane.showMessageDialog(this, "Gmail incorrecto", "ERROR",JOptionPane.ERROR_MESSAGE);
          return;
        }
        
        if(user == false){
           JOptionPane.showMessageDialog(this, "Usuario incorrecto", "ERROR",JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        if(password == false){
           JOptionPane.showMessageDialog(this, "Contraseña incorrecto", "ERROR",JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        if (gMail == true && user == true && password == true) { 

            // Simplemente llama al nuevo método
            attemptProfileUpdate();
            addTextInTheProfile();

        } else {
            // Aquí van tus otros JOptionPane de error
            if (gMail == false) {
                JOptionPane.showMessageDialog(this, "Gmail incorrecto", "ERROR", JOptionPane.ERROR_MESSAGE);
                return; 
            }

            if (user == false) {
                JOptionPane.showMessageDialog(this, "Usuario incorrecto", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (password == false) {
                JOptionPane.showMessageDialog(this, "Contraseña incorrecto", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void check(JTextField a, JButton muestra, JButton esconde) {
        a.setEditable(false);
        a.setCaretColor(new java.awt.Color(0,0,0,0));
        muestra.setVisible(true);
        esconde.setVisible(false);
    }
    
    public void edit(JTextField a, JButton muestra, JButton esconde) {
        a.setEditable(true);
        a.setCaretColor(new java.awt.Color(0,0,0));
        muestra.setVisible(true);
        esconde.setVisible(false);
    }
    
    public boolean validateAge(String date) {
        return !date.matches("[1-9][0-9]|1[01][1-9]|120");
    }
    
    class FondoPanel extends JPanel {
        private Image image;
        
        @Override
        public void paint(Graphics graphics) {
            image = new ImageIcon(getClass().getResource("/Images/BackgroundProfileUser.jpg")).getImage();
            
            graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(graphics);
        }
    }
    
    public void addTextInTheProfile() {
        String nameComplet = cliente.getName() + cliente.getLastName();
        jlNameLastname.setText(nameComplet);
        
        String gender;
        if (cliente.getGender() == 'M') {
            gender = "Masculino";
            jlGender.setText(gender);
        }else if(cliente.getGender() == 'F') {
            gender = "Femenino";
            jlGender.setText(gender);
        }else {
            gender = "Otro";
            jlGender.setText(gender);
        }
        
        jlCode.setText(this.cliente.getCodClient());
        txtGmail.setText(this.cliente.getGmail());
        txtAge.setText(String.valueOf(this.cliente.getAge()));
        txtCountry.setText(this.cliente.getCountry());
        txtUsername.setText(this.cliente.getUsername());
        txtPassword.setText(this.cliente.getPassword());
        txtDescription.setText(this.cliente.getDescription());
    }
    
    private void attemptProfileUpdate() {

        String codigoCliente = jlCode.getText();
        
        Client client = new Client(); 

        // Llenamos el objeto con los datos de los campos de texto
        client.setCodClient(codigoCliente);
        client.setName(this.cliente.getName());
        client.setLastName(this.cliente.getLastName());
        client.setGmail(txtGmail.getText());
        client.setUsername(this.cliente.getUsername());
        client.setPassword(new String(txtPassword.getPassword())); 
        client.setCountry(txtCountry.getText()); 
        client.setDescription(txtDescription.getText()); 

        // --- Manejo de campos especiales (según mi metodo 'mergeClientData') ---

        // CAMPOS NUMÉRICOS (Edad)
        try {
            int age = Integer.parseInt(txtAge.getText());
            client.setAge(age > 0 ? age : 0); // Asigna la edad solo si es positiva
        } catch (NumberFormatException e) {
            client.setAge(0); // Si está vacío o no es número, envía 0 (sin cambio)
        }

        // CAMPOS DE CARACTER (Género)
        String generoStr = jlGender.getText(); 
        if (generoStr != null && !generoStr.isEmpty()) {
            client.setGender(generoStr.charAt(0));
        } else {
            client.setGender('\u0000'); // Envía '\u0000' (sin cambio)
        }

        // --- LLAMA AL MÉTODO DE ACTUALIZACIÓN ---
        boolean actualizado = cc.updatePartially(codigoCliente, client);

        if (actualizado) {
            
            this.cliente.setCodClient(client.getCodClient());
            this.cliente.setName(client.getName());
            this.cliente.setLastName(client.getLastName());
            this.cliente.setGender(client.getGender());
            this.cliente.setCountry(client.getCountry());
            this.cliente.setGmail(client.getGmail());
            this.cliente.setUsername(client.getUsername());
            this.cliente.setPassword(client.getPassword());
            this.cliente.setDescription(client.getDescription());
            
            JOptionPane.showMessageDialog(this, "Perfil actualizado correctamente.");
            
            CurrencyConverter converter = new CurrencyConverter(); // Renombré 'cc' para evitar confusión
            converter.setVisible(true);
            converter.setLocationRelativeTo(null);
            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo encontrar o actualizar el perfil.", "Error", JOptionPane.ERROR_MESSAGE);
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAge;
    private javax.swing.JButton btnCheckCountry;
    private javax.swing.JButton btnCheckDescription;
    private javax.swing.JButton btnCheckGmail;
    private javax.swing.JButton btnCheckPassword;
    private javax.swing.JButton btnCheckUser;
    private javax.swing.JButton btnDisguisePass;
    private javax.swing.JButton btnEditAge;
    private javax.swing.JButton btnEditCountry;
    private javax.swing.JButton btnEditDescription;
    private javax.swing.JButton btnEditGmail;
    private javax.swing.JButton btnEditPassword;
    private javax.swing.JButton btnEditUsername;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnShowPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlGender;
    private javax.swing.JLabel jlNameLastname;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
