/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerCoins;
import Controller.ControllerRecord;
import Model.RecordUserModel;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class RecordUser extends javax.swing.JFrame {
    FondoPanel fondoPanel = new FondoPanel();
    ControllerRecord listRecord = ControllerRecord.getInstance();
    /**
     * Creates new form RecordUser
     */
    public RecordUser() {
        this.setContentPane(fondoPanel);
        initComponents();
        updateTableRecord();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtRecordUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtRecordUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Hour", "Rate", "Country Origin", "Country Destination", "Amount to Convert", "Conversion Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtRecordUser.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jtRecordUser);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Exchange Record");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 854, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CurrencyConverter cc = new CurrencyConverter();
        cc.setVisible(true);
        cc.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    class FondoPanel extends JPanel {
        private Image image;
        
        @Override
        public void paint(Graphics graphics) {
            image = new ImageIcon(getClass().getResource("/Images/BackgroundRecorUser.jpg")).getImage();
            
            graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(graphics);
        }
    }

    public Object[][] getRecordDataForTable() {
        
        int rowTableFullData = listRecord.getListRecord().size();//obtenemos todos los datos de la lista
        
        final int MAX_ROWS = 10; //filas totales a mostrar
        
        final int COLUMN_TABLE = 6; //columnas totales a mostrar
        
        int rowTable = Math.min(rowTableFullData, MAX_ROWS); // calculamos el tamaño de la tabla para las 10 filas
        
        Object[][] data = new Object[rowTable][COLUMN_TABLE];
        
        // Calcular el índice de inicio. Si la lista tiene 15 elementos (fullListSize=15)
        // queremos empezar en el índice 5 (15 - 10 = 5) para mostrar del 5 al 14.
        int startIndex = rowTableFullData - rowTable;
        
        for (int i = 0; i < rowTable; i++) {
            
            RecordUserModel records = listRecord.getListRecord().get(startIndex + i);//el indice real a buscar en la lista es startIndex + i
            
            // Si el registro existe (tu getElementList devuelve null si está fuera de rango)
            if (records != null) {
                data[i][0] = records.getCurrentDate();
                data[i][1] = records.getCurrentHour();
                data[i][2] = records.getBase_code();
                data[i][3] = records.getTarget_code();
                data[i][4] = records.getAmountToConvert();
                data[i][5] = records.getConversionResult();
            } else {
                // Manejar caso donde el índice es inválido (aunque con startIndex + i no debería pasar)
                System.err.println("Error: Registro en índice inválido.");
            }
            
        }
        
        return data;
    }
    
    public void updateTableRecord(){
        String camposTable[] = {"Date", "Hour", "Country Origin", "Country Destination", "Amount to Convert"
                                    , "Conversion Result"};
        
        Object[][] recordData = getRecordDataForTable();
        
        DefaultTableModel tableModel = new DefaultTableModel(recordData, camposTable){
        
            @Override
            public boolean isCellEditable(int row, int column) {
                // Esto le dice a la JTable que NINGUNA celda se puede editar
                return false;
            }
            
        };
        
        jtRecordUser.setModel(tableModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtRecordUser;
    // End of variables declaration//GEN-END:variables
}
