/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerClients;
import Model.Client;
import Model.Clock;
import SaveData.ClientRepositoryCSV;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class SingUpUser extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    Clock localTime = new Clock();
    ControllerClients nc = ControllerClients.getInstance();
    
    
    /**
     * Creates new form SingUpUser
     */
    public SingUpUser() {
        this.setContentPane(fondo);
        
        initComponents();
        this.lbDisguise.setVisible(false);
        this.txtPassword.setEchoChar('⚫');
        showTimeAndDate();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    //metodo para colocar la hora y las fechas en los label y que se actualicen automaticamente
    public void showTimeAndDate() {

        jlDate.setText(localTime.getDate());
        jlTime.setText(localTime.getTime());

        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jlDate.setText(localTime.getDate());
                jlTime.setText(localTime.getTime());
            }
        };

        Timer timer = new Timer(1000, action);
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSingup = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jcCountry = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        btnReturn = new javax.swing.JButton();
        lbShow = new javax.swing.JLabel();
        lbDisguise = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlTime = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcGender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Sing Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 160, -1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Gmail:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Age:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Country:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("Username:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("Password:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 60, -1));

        btnSingup.setBackground(new java.awt.Color(0, 0, 0));
        btnSingup.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        btnSingup.setForeground(new java.awt.Color(255, 255, 102));
        btnSingup.setText("Sing Up");
        btnSingup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102)));
        btnSingup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingupActionPerformed(evt);
            }
        });
        jPanel1.add(btnSingup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 114, -1));

        txtName.setBackground(new java.awt.Color(0, 102, 255));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 240, -1));

        txtGmail.setBackground(new java.awt.Color(0, 102, 255));
        txtGmail.setForeground(new java.awt.Color(255, 255, 255));
        txtGmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        jPanel1.add(txtGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 240, -1));

        txtLastName.setBackground(new java.awt.Color(0, 102, 255));
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 240, -1));

        txtAge.setBackground(new java.awt.Color(0, 102, 255));
        txtAge.setForeground(new java.awt.Color(255, 255, 255));
        txtAge.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 240, -1));

        txtUsername.setBackground(new java.awt.Color(0, 102, 255));
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("usuario01@nemesis.com");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 240, -1));

        jcCountry.setBackground(new java.awt.Color(0, 102, 255));
        jcCountry.setForeground(new java.awt.Color(255, 255, 255));
        jcCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Brasil", "Canada", "Colombia", "Chile", "China", "España", "E.E.U.U.", "Francia", "Japon", "Mexico", "Peru", "Reino Unido", "Suiza" }));
        jcCountry.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, java.awt.Color.black));
        jcCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcCountry.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(jcCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 92, -1));

        txtPassword.setBackground(new java.awt.Color(0, 102, 255));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 240, -1));

        btnReturn.setBackground(new java.awt.Color(0, 0, 0));
        btnReturn.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 102));
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        btnReturn.setBorder(null);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 24, 24));

        lbShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver_32px.png"))); // NOI18N
        lbShow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbShowMouseClicked(evt);
            }
        });
        jPanel1.add(lbShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        lbDisguise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocultar_32px.png"))); // NOI18N
        lbDisguise.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDisguise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDisguiseMouseClicked(evt);
            }
        });
        jPanel1.add(lbDisguise, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jlDate.setForeground(new java.awt.Color(255, 255, 255));
        jlDate.setText("10/12/2025");
        jlDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 255, 204)));
        jPanel1.add(jlDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hora:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jlTime.setForeground(new java.awt.Color(255, 255, 255));
        jlTime.setText("12:20");
        jlTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 255, 204)));
        jPanel1.add(jlTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 20, 50, -1));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 102));
        jLabel10.setText("Genero:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jcGender.setBackground(new java.awt.Color(0, 102, 255));
        jcGender.setForeground(new java.awt.Color(255, 255, 255));
        jcGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        jPanel1.add(jcGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 290, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyReleased

    private void lbShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbShowMouseClicked
        // TODO add your handling code here:
        lbShow.setVisible(false);
        lbDisguise.setVisible(true);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lbShowMouseClicked

    private void lbDisguiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDisguiseMouseClicked
        // TODO add your handling code here:
        lbDisguise.setVisible(false);
        lbShow.setVisible(true);
        txtPassword.setEchoChar('⚫');
    }//GEN-LAST:event_lbDisguiseMouseClicked

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        LoginUser lu = new LoginUser();
        lu.setVisible(true);
        lu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnSingupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingupActionPerformed
        // TODO add your handling code here:
        try {
            //validamos que los campos sean llenados y que no queden vacios
            if (txtAge.getText().length() == 0 || txtGmail.getText().length() == 0 || txtLastName.getText().length() == 0 
                    || txtName.getText().length() == 0 || txtPassword.getText().length() == 0 || txtUsername.getText().length() == 0) {
                
                JOptionPane.showMessageDialog(this, "Hay campos que faltan llenar", "ERROR", JOptionPane.ERROR_MESSAGE);
                
            }else if (validateFirstAndLastname(txtName.getText().trim()) || validateFirstAndLastname(txtLastName.getText().trim())) {
                
                //validamos los nombres y apellidos
                JOptionPane.showMessageDialog(this, "Los nombres o apellidos no pueden contener simbolos o numeros", "ERROR"
                        , JOptionPane.ERROR_MESSAGE);
                
            }else if (validateAge(txtAge.getText().trim())) {
                
                //validamos la edad
                JOptionPane.showMessageDialog(this, "Edad ingresada es incorrecta, la edad minima es de 10 años"
                        ,"ERROR" ,JOptionPane.ERROR_MESSAGE);
                
            }else{
            
                //validamos el correo gmail
                String email = txtGmail.getText();
                 if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$")) {
                     
                     JOptionPane.showMessageDialog(this, "Ingrese un correo electrónico válido.");
                    return;
                    
                }else{

                    //validamos el campo del username
                    boolean user = false;
                    Pattern patronUsuario = Pattern.compile("^\\w+@nemesis\\.com$");
                    Matcher users = patronUsuario.matcher(txtUsername.getText());
                    user = users.matches();

                    //validamos el campo del password
                    boolean password = false;
                    Pattern patronPassword=Pattern.compile("\\S{8,}");
                    String textPass = new String(txtPassword.getPassword());
                    Matcher passwords = patronPassword.matcher(textPass);
                    password = passwords.matches();
                    
                    //validamos que se cumplan las condiciones
                    if(user == false || password == false){
                        
                          JOptionPane.showMessageDialog(this, "Contraseña o usuario incorrecto", "ERROR",JOptionPane.ERROR_MESSAGE);
                          return;
                          
                    }
                    
                    Client cliente = new Client();
                    cliente.setCodClient(nc.generateCodeUniqueClient(4));
                    cliente.setName(txtName.getText());
                    cliente.setLastName(txtLastName.getText());
                    cliente.setGmail(txtGmail.getText());
                    
                    String ageText = txtAge.getText();
                    if (ageText.isEmpty()) {
                        cliente.setAge(0); // O un valor por defecto si está vacío
                    } else {
                        cliente.setAge(Integer.parseInt(ageText));
                    }
                    
                    cliente.setCountry(jcCountry.getSelectedItem().toString());
                    if (jcGender.getSelectedItem().toString().equals("Masculino")) {
                        cliente.setGender('M');
                    }else if(jcGender.getSelectedItem().toString().equals("Femenino")){
                        cliente.setGender('F');
                    }else {
                        cliente.setGender('N');
                    }
                    cliente.setUsername(txtUsername.getText());
                    cliente.setPassword(txtPassword.getText());
                    
                    ControllerClients.getInstance().addClientsInList(cliente);                     
                    //volvemos a la ventana anterior
                    LoginUser lu = new LoginUser();
                    lu.setVisible(true);
                    lu.setLocationRelativeTo(null);
                    this.setVisible(false);
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSingupActionPerformed

    class FondoPanel extends JPanel {
        private Image image;
        
        @Override
        public void paint(Graphics graphics) {
            image = new ImageIcon(getClass().getResource("/Images/FondoRegistroUser.jpg")).getImage();
            
            graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(graphics);
        }
    }
    
    public boolean validateFirstAndLastname(String datos){
        return !datos.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ]+( [a-zA-ZáéíóúÁÉÍÓÚñÑ]+)*$");
    }
    
    public boolean validateAge(String date) {
        return !date.matches("[1-9][0-9]|1[01][1-9]|120");
    }
    
    public void clearFields() {
        txtAge.setText("");
        txtGmail.setText("");
        txtLastName.setText("");
        txtName.setText("");
        txtPassword.setText("");
        txtUsername.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSingup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcCountry;
    private javax.swing.JComboBox<String> jcGender;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlTime;
    private javax.swing.JLabel lbDisguise;
    private javax.swing.JLabel lbShow;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
