/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ImgSplashCode;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class Splash extends javax.swing.JFrame {
    
    private Color transparent;
    private Point point;
    /**
     * Creates new form Splash
     */
    public Splash() {
        transparent = new Color(0,0,0,0);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setBackground(transparent);
        
        ImgSplashCode myBackground = new ImgSplashCode(jpBackground, "/Images/splash.png");
        jpBackground.add(myBackground).repaint();
        jpBackground.setOpaque(false);
        jpBackground.setBorder(null);
        jpBackground.setBackground(transparent);
        
        //agregamos el metodo progressbarinitial
        progressBarInitial();
    }
    
    private void progressBarInitial() {
        Timer timer = new Timer(45,(e) -> {
            //cambiamos el valor en cada intervalo
            jpStarting.setValue(jpStarting.getValue() + 1);
            
            //colocamos un color a la carga
            jpStarting.setBackground(Color.DARK_GRAY);
            jpStarting.setForeground(Color.GREEN);
            
            //colocamos un texto dentro de nuestro progresbar, pero primero activamos la propiedad
            jpStarting.setStringPainted(true);
            
            //colocamos el texto dentro de nuestro progressbar
            jpStarting.setString("Loading...." + jpStarting.getValue() + "%");
        });
        
        //iniciamos el Timer
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackground = new javax.swing.JPanel();
        jlNameCompany = new javax.swing.JLabel();
        jpStarting = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpBackgroundMouseDragged(evt);
            }
        });
        jpBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpBackgroundMousePressed(evt);
            }
        });

        jlNameCompany.setFont(new java.awt.Font("Old English Text MT", 3, 24)); // NOI18N
        jlNameCompany.setForeground(new java.awt.Color(0, 255, 51));
        jlNameCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNameCompany.setText("Nemesis");
        jlNameCompany.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlNameCompany.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jpBackgroundLayout = new javax.swing.GroupLayout(jpBackground);
        jpBackground.setLayout(jpBackgroundLayout);
        jpBackgroundLayout.setHorizontalGroup(
            jpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackgroundLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBackgroundLayout.createSequentialGroup()
                        .addComponent(jlNameCompany)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBackgroundLayout.createSequentialGroup()
                        .addComponent(jpStarting, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jpBackgroundLayout.setVerticalGroup(
            jpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackgroundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlNameCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jpStarting, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBackgroundMousePressed
        // TODO add your handling code here:
        //guardamos el dato del movimiento en una variable point usando evt.getPoint()
        point = evt.getPoint();
        
        // sobreescribimos el dato
        getComponentAt(point);
    }//GEN-LAST:event_jpBackgroundMousePressed

    private void jpBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBackgroundMouseDragged
        // TODO add your handling code here:
        //calculamos las nuevas coordenadas x y y en nuestro formulario
        
        //guardamos las posiciones de x y y actuales en variables
        int currentX = this.getLocation().x;
        int currentY = this.getLocation().y;
        
        //calculamos el movimiento en x y y a travez de este evento y lo guardamos en variables
        int moveX = (currentX + evt.getX()) - (currentX + point.x);
        int moveY = (currentY + evt.getY()) - (currentY + point.y);
        
        //calculamos la nueva posicion en x y y
        int x = currentX+ moveX;
        int y = currentY+ moveY;
        
        // pasamos las nuevas posiciones x y y
        this.setLocation(x, y);
    }//GEN-LAST:event_jpBackgroundMouseDragged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlNameCompany;
    private javax.swing.JPanel jpBackground;
    private javax.swing.JProgressBar jpStarting;
    // End of variables declaration//GEN-END:variables
}
