/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerCoins;
import Controller.ConverterNamesCountryToCodeAPI;
import Model.Clock;
import Model.Rates;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.time.temporal.TemporalQueries.localTime;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ViewRatesUser extends javax.swing.JFrame {
    FondoPanel fondoPanel = new FondoPanel();
    Clock localTime = new Clock();
    ControllerCoins cc = new ControllerCoins();
    String selectedCountry = "ARS";
    List<Rates> result = cc.showRatesOfTheCountry(selectedCountry);
    
    /**
     * Creates new form ViewRatesUser
     */
    public ViewRatesUser() {
        this.setContentPane(fondoPanel);
        initComponents();
        
        showTimeAndDate();
        
        updateJTableRates(result);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRate = new javax.swing.JTable();
        jtReturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlHour = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcCountry = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Rates");

        jtRate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Country", "Country Abbrevation", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtRate);

        jtReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        jtReturn.setBorder(null);
        jtReturn.setContentAreaFilled(false);
        jtReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtReturnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jlDate.setForeground(new java.awt.Color(255, 255, 255));
        jlDate.setText("13/12/2025");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora:");

        jlHour.setForeground(new java.awt.Color(255, 255, 255));
        jlHour.setText("12:00:00");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pais:");

        jcCountry.setBackground(new java.awt.Color(0, 0, 0));
        jcCountry.setForeground(new java.awt.Color(255, 255, 255));
        jcCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Brasil", "Canada", "Colombia", "Chile", "China", "España", "Estados Unidos", "Francia", "Japon", "Mexico", "Peru", "Reino Unido", "Suiza" }));
        jcCountry.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtReturn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlDate)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlHour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtReturn)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jlDate)
                        .addComponent(jLabel4)
                        .addComponent(jlHour)
                        .addComponent(jLabel6)
                        .addComponent(jcCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtReturnActionPerformed
        // TODO add your handling code here:
        CurrencyConverter cc = new CurrencyConverter();
        cc.setVisible(true);
        cc.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jtReturnActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchRates = jcCountry.getSelectedItem().toString();
        if (searchRates.isEmpty()) {
            // No hacer nada o mostrar un mensaje de error al usuario
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un código de moneda válido.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return; // Detiene la ejecución
        }
        
        String codeAPI = ConverterNamesCountryToCodeAPI.getCodeForCountryName(searchRates);
        
        result = cc.showRatesOfTheCountry(codeAPI);
        
        updateJTableRates(result);
        
    }//GEN-LAST:event_btnSearchActionPerformed
    
    class FondoPanel extends JPanel {
        private Image image;
        
        @Override
        public void paint(Graphics graphics) {
            image = new ImageIcon(getClass().getResource("/Images/BackgroundViewRatesUser.jpg")).getImage();
            
            graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(graphics);
        }
    }
    
    public void showTimeAndDate() {

        jlDate.setText(localTime.getDate());
        jlHour.setText(localTime.getTime());

        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jlDate.setText(localTime.getDate());
                jlHour.setText(localTime.getTime());
            }
        };

        Timer timer = new Timer(1000, action);
        timer.start();
    }
    
    public void updateJTableRates(List<Rates> tasasDetalladas) {

        // 1. Obtener el modelo de datos de la tabla 'jtRates'
        DefaultTableModel modelo = (DefaultTableModel) jtRate.getModel();

        // 2. Limpiar contenido anterior: Es esencial antes de cargar nuevos datos.
        modelo.setRowCount(0); 

        // 3. Iterar y Añadir Fila por Fila
        for (Rates rate : tasasDetalladas) {

            // Creamos un array de Object con los 3 datos por fila:
            // [CÓDIGO, PAÍS/MONEDA, TASA]
            Object[] fila = new Object[3];

            // Fila[0]: Código de Moneda
            fila[0] = rate.getAbbreviatonCoin(); 

            // Fila[1]: Nombre del País
            // (Si el campo 'country' de Rates fue modificado a String, solo usa .getCountry())
            fila[1] = rate.getCountry(); 

            // Fila[2]: Tasa
            fila[2] = rate.getRate(); 

            // 4. Agregar la fila al modelo.
            modelo.addRow(fila);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcCountry;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlHour;
    private javax.swing.JTable jtRate;
    private javax.swing.JButton jtReturn;
    // End of variables declaration//GEN-END:variables
}
